stages:
- test
- build

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - public/css/app.css
  - public/js/app.js
  - public/js/manifest.js
  - public/js/vendor.js
  - public/*/vendor/
  - node_modules/
  - vendor/

include:
- .gitlab-test.yml
- .gitlab-docker-x86_64.yml
